<div class="row">
	<div class="alert alert-default">
		<div class="well">
			<p>Quisque eleifend et nisl id viverra. Integer in lacus ipsum. Nulla dignissim suscipit justo nec facilisis. Morbi quis urna in lectus convallis consequat. Nunc lobortis bibendum scelerisque. Pellentesque aliquam cursus enim, ac imperdiet nunc tincidunt ac. Integer semper odio at sollicitudin tristique. Pellentesque malesuada nulla eget sem consectetur, eget imperdiet dui tincidunt. Phasellus ut scelerisque erat. Etiam vel augue ut nisl eleifend luctus id in purus. Duis a mattis dui. Duis orci libero, accumsan vel aliquet et, volutpat vel sapien. Nunc eget diam ligula.</p>

			<p>Vivamus molestie consequat porttitor. Sed fermentum enim at orci accumsan blandit. Suspendisse vitae diam et erat finibus pharetra. Proin augue nisl, lacinia eget justo in, pretium congue sem. Nulla et accumsan sapien. Quisque quis sagittis mi. Phasellus sollicitudin nec metus at rutrum. Morbi a mi dignissim, molestie magna vitae, ullamcorper nisl.</p>
		
			<hr>

			<ul class="list-group">
				<li class="list-group-item">Donec at tortor et dui ultrices scelerisque nec ut ipsum.</li>
				<li class="list-group-item">Cras vitae orci laoreet, hendrerit dolor non, egestas est.</li>
				<li class="list-group-item">Fusce scelerisque nunc sed auctor aliquet.</li>
				<li class="list-group-item">Donec quis mauris et ipsum posuere pretium at at mi.</li>
				<li class="list-group-item">Nulla eu velit et arcu posuere iaculis sed ut diam.</li>
				<li class="list-group-item">Aenean dignissim ante a libero tincidunt, ac aliquam turpis consequat.</li>
			</ul>
		</div>
	</div>				
</div>